# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pic_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(400, 400)
        Dialog.setMinimumSize(QtCore.QSize(325, 400))
        Dialog.setMaximumSize(QtCore.QSize(400, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelname = QtWidgets.QLabel(Dialog)
        self.labelname.setText("")
        self.labelname.setObjectName("labelname")
        self.horizontalLayout_3.addWidget(self.labelname)
        self.pushButton_pic = QtWidgets.QPushButton(Dialog)
        self.pushButton_pic.setObjectName("pushButton_pic")
        self.horizontalLayout_3.addWidget(self.pushButton_pic)
        self.pushButton_show = QtWidgets.QPushButton(Dialog)
        self.pushButton_show.setObjectName("pushButton_show")
        self.horizontalLayout_3.addWidget(self.pushButton_show)
        self.pushButton_del = QtWidgets.QPushButton(Dialog)
        self.pushButton_del.setObjectName("pushButton_del")
        self.horizontalLayout_3.addWidget(self.pushButton_del)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.pushButton_ok.clicked.connect(Dialog.accept) # type: ignore
        self.pushButton_cancel.clicked.connect(Dialog.reject) # type: ignore
        self.pushButton_del.clicked.connect(Dialog.delete_selected) # type: ignore
        self.pushButton_pic.clicked.connect(Dialog.add_picture) # type: ignore
        self.pushButton_show.clicked.connect(Dialog.show_selected) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton_pic, self.pushButton_show)
        Dialog.setTabOrder(self.pushButton_show, self.pushButton_del)
        Dialog.setTabOrder(self.pushButton_del, self.listWidget)
        Dialog.setTabOrder(self.listWidget, self.pushButton_ok)
        Dialog.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Pictures"))
        self.pushButton_pic.setText(_translate("Dialog", "Add picture"))
        self.pushButton_show.setText(_translate("Dialog", "Show selected"))
        self.pushButton_del.setText(_translate("Dialog", "delete selected"))
        self.pushButton_ok.setText(_translate("Dialog", "OK"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
