# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redactionitca.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(800, 700)
        Dialog.setMinimumSize(QtCore.QSize(700, 700))
        Dialog.setMaximumSize(QtCore.QSize(1000, 1000))
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_previous = QtWidgets.QPushButton(Dialog)
        self.pushButton_previous.setEnabled(False)
        self.pushButton_previous.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_previous.setCheckable(False)
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.horizontalLayout.addWidget(self.pushButton_previous)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_next = QtWidgets.QPushButton(Dialog)
        self.pushButton_next.setEnabled(False)
        self.pushButton_next.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_next.setObjectName("pushButton_next")
        self.horizontalLayout.addWidget(self.pushButton_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_page = QtWidgets.QVBoxLayout()
        self.verticalLayout_page.setObjectName("verticalLayout_page")
        self.verticalLayout.addLayout(self.verticalLayout_page)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setMinimumSize(QtCore.QSize(0, 3))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_cmd = QtWidgets.QHBoxLayout()
        self.horizontalLayout_cmd.setObjectName("horizontalLayout_cmd")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_cmd.addItem(spacerItem)
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_cmd.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_cmd.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_cmd.addItem(spacerItem1)
        self.pushButton_new = QtWidgets.QPushButton(Dialog)
        self.pushButton_new.setObjectName("pushButton_new")
        self.horizontalLayout_cmd.addWidget(self.pushButton_new)
        self.verticalLayout.addLayout(self.horizontalLayout_cmd)

        self.retranslateUi(Dialog)
        self.pushButton_cancel.clicked.connect(Dialog.reject) # type: ignore
        self.pushButton_ok.clicked.connect(Dialog.accept) # type: ignore
        self.pushButton_new.clicked.connect(Dialog.add_redaction_widget) # type: ignore
        self.pushButton_next.clicked.connect(Dialog.next_page) # type: ignore
        self.pushButton_previous.clicked.connect(Dialog.previous_page) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButton_ok, self.pushButton_cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "NEW ITCA"))
        self.pushButton_previous.setText(_translate("Dialog", "<"))
        self.label.setText(_translate("Dialog", "REDACTION"))
        self.pushButton_next.setText(_translate("Dialog", "2 >"))
        self.pushButton_ok.setText(_translate("Dialog", "Next"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
        self.pushButton_new.setText(_translate("Dialog", "Nouvelle étape"))
